services:
  - type: web
    name: customer-support-ticket-system
    runtime: node
    buildCommand: >
      npm install --prefix frontend --legacy-peer-deps &&
      npm run build --prefix frontend &&
      npm install --prefix backend
    startCommand: node backend/server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
