require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const https = require('https');

/**
 * Design Phase Agent (Solution Architect Persona)
 * - Generates Architecture, HLD, LLD, and Wireframe documents
 * - Publishes all artifacts to Confluence
 */

const CONF_BASE = process.env.CONFLUENCE_BASE_URL;
const CONF_SPACE = process.env.CONFLUENCE_SPACE_KEY;
const JIRA_EMAIL = process.env.JIRA_EMAIL;
const JIRA_TOKEN = process.env.JIRA_API_TOKEN;

function confluenceRequest(method, path, body = null) {
  return new Promise((resolve, reject) => {
    const auth = Buffer.from(`${JIRA_EMAIL}:${JIRA_TOKEN}`).toString('base64');
    const url = new URL(CONF_BASE + path);
    const options = {
      hostname: url.hostname,
      path: url.pathname + url.search,
      method,
      headers: {
        'Authorization': `Basic ${auth}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
    };
    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => {
        try { resolve({ status: res.statusCode, body: JSON.parse(data) }); }
        catch { resolve({ status: res.statusCode, body: data }); }
      });
    });
    req.on('error', reject);
    if (body) req.write(JSON.stringify(body));
    req.end();
  });
}

async function findPage(title) {
  const encoded = encodeURIComponent(title);
  const res = await confluenceRequest('GET', `/rest/api/content?title=${encoded}&spaceKey=${CONF_SPACE}&expand=version`);
  if (res.status === 200 && res.body.results?.length > 0) return res.body.results[0];
  return null;
}

async function createConfluencePage(title, content, parentId = null) {
  // Check if page already exists — update it instead of creating a duplicate
  const existing = await findPage(title);
  if (existing) {
    const nextVersion = (existing.version?.number || 1) + 1;
    const body = {
      type: 'page',
      title,
      version: { number: nextVersion },
      body: { storage: { value: content, representation: 'storage' } },
    };
    const res = await confluenceRequest('PUT', `/rest/api/content/${existing.id}`, body);
    if (res.status !== 200) throw new Error(`Confluence page update failed (${res.status}): ${JSON.stringify(res.body)}`);
    const webLink = CONF_BASE + res.body._links?.webui;
    console.log(`[design] Updated: "${title}" (v${nextVersion}) → ${webLink}`);
    return res.body;
  }

  // Create new page
  const body = {
    type: 'page',
    title,
    space: { key: CONF_SPACE },
    body: { storage: { value: content, representation: 'storage' } },
    ...(parentId ? { ancestors: [{ id: parentId }] } : {}),
  };
  const res = await confluenceRequest('POST', '/rest/api/content', body);
  if (res.status !== 200 && res.status !== 201) {
    throw new Error(`Confluence page creation failed (${res.status}): ${JSON.stringify(res.body)}`);
  }
  const webLink = CONF_BASE + res.body._links?.webui;
  console.log(`[design] Created: "${title}" → ${webLink}`);
  return res.body;
}

// ──────────────────────────────────────────────────────────────
// Document content
// ──────────────────────────────────────────────────────────────

const ARCHITECTURE_CONTENT = `
<h2>System Architecture — AI-Enhanced Customer Support Ticket System</h2>
<p><em>Generated by AI Solution Architect Agent | SDLC Phase 3 — Design | Project: mm-learning-group-1</em></p>

<h3>Architecture Overview</h3>
<p>Three-tier architecture: React 18 SPA frontend, Node.js 24 / Express 4 REST API backend, and SQLite database (via Node.js built-in <code>node:sqlite</code>). An AI layer powered by Claude API (via CodeMie MCP) provides ticket triage, priority scoring, and auto-response capabilities.</p>

<h3>System Components</h3>
<table>
  <tbody>
    <tr><th>Component</th><th>Technology</th><th>Responsibility</th></tr>
    <tr><td>Frontend</td><td>React 18</td><td>Ticket submission form, list view, analytics dashboard, filter tabs</td></tr>
    <tr><td>Backend API</td><td>Node.js 24 / Express 4</td><td>REST endpoints, business logic, AI integration, SLA enforcement</td></tr>
    <tr><td>Database</td><td>SQLite (node:sqlite built-in)</td><td>Ticket storage, response history, SLA records — zero-config, file-based</td></tr>
    <tr><td>AI Layer</td><td>Claude API via CodeMie MCP</td><td>Ticket triage, priority scoring, auto-response drafts</td></tr>
    <tr><td>SDLC Orchestrator</td><td>Node.js workflow scripts</td><td>Agent selection, HITL routing, retry logic, self-healing QA automation</td></tr>
    <tr><td>Testing</td><td>Playwright</td><td>E2E tests with self-healing selector repair</td></tr>
    <tr><td>CI/CD</td><td>GitHub Actions</td><td>Build, test, artifact packaging on every push to main</td></tr>
    <tr><td>Integrations</td><td>JIRA REST API v3, Confluence REST API</td><td>Issue tracking, documentation publishing</td></tr>
  </tbody>
</table>

<h3>Architecture Diagram (logical)</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
┌─────────────────────────────────────────────────────────────┐
│                        BROWSER                              │
│   React 18 SPA (port 3000)                                  │
│   TicketForm | TicketList | Dashboard | FilterTabs          │
└──────────────────────┬──────────────────────────────────────┘
                       │ REST (fetch /api/*)
┌──────────────────────▼──────────────────────────────────────┐
│               Node.js 24 / Express 4 (port 3001)            │
│   /api/tickets  /api/tickets/:id/triage                     │
│   /api/analytics  /api/tickets/:id/suggest-reply            │
│              ┌───────────────────────┐                      │
│              │  AI Services (Claude) │                      │
│              │  triage / scoring     │                      │
│              │  auto-response drafts │                      │
│              └───────────┬───────────┘                      │
└──────────────────────────┼──────────────────────────────────┘
                           │
┌──────────────────────────▼──────────────────────────────────┐
│          SQLite (node:sqlite built-in)                      │
│   tickets | responses | sla_records                         │
└─────────────────────────────────────────────────────────────┘
]]></ac:plain-text-body></ac:structured-macro>

<h3>Key Design Decisions</h3>
<ul>
  <li><strong>node:sqlite over better-sqlite3:</strong> Node v24 built-in eliminates C++ native compilation (no Visual Studio / node-gyp dependency).</li>
  <li><strong>REST over GraphQL:</strong> Simpler toolchain; sufficient for CRUD + analytics endpoints at this scale.</li>
  <li><strong>Claude API server-side only:</strong> Keeps API keys server-side, never exposed to the browser.</li>
  <li><strong>data-testid attributes on all interactive elements:</strong> Enables stable Playwright selectors with self-healing fallback.</li>
  <li><strong>File-based SQLite:</strong> Zero ops overhead for capstone; trivially replaceable with PostgreSQL for production.</li>
</ul>
`;

const HLD_CONTENT = `
<h2>High Level Design — AI-Enhanced CSTS</h2>
<p><em>Generated by AI Solution Architect Agent | SDLC Phase 3 — Design</em></p>

<h3>Data Flow</h3>
<ol>
  <li>User submits ticket via React form → POST /api/tickets</li>
  <li>Express API validates and persists to SQLite</li>
  <li>AI triage service (Claude API) assigns category and priority score</li>
  <li>SLA timer starts based on priority: High = 4h, Medium = 8h, Low = 24h</li>
  <li>Agent is notified (or auto-assigned by queue depth)</li>
  <li>Agent views AI-suggested reply in the ticket detail panel</li>
  <li>Analytics dashboard aggregates ticket volume, resolution time, SLA breach rate</li>
</ol>

<h3>Sprint-to-Component Mapping</h3>
<table>
  <tbody>
    <tr><th>Sprint</th><th>Stories</th><th>New Components</th><th>New DB Fields</th></tr>
    <tr><td>Sprint 1</td><td>KAN-3 Triage, KAN-7 Priority</td><td>CategoryBadge, PriorityBadge</td><td>category, priority</td></tr>
    <tr><td>Sprint 2</td><td>KAN-11 SLA</td><td>SLACountdown, AlertBanner</td><td>sla_due_at, sla_breached</td></tr>
    <tr><td>Sprint 3</td><td>KAN-19 Auto-Response, KAN-15 Analytics</td><td>SuggestedReply, Dashboard, Charts</td><td>responses table</td></tr>
  </tbody>
</table>

<h3>Integration Points</h3>
<table>
  <tbody>
    <tr><th>Integration</th><th>Auth</th><th>Usage</th></tr>
    <tr><td>JIRA REST API v3</td><td>Basic (email:token)</td><td>Create EPICs, Stories, Tasks from BA agent</td></tr>
    <tr><td>Confluence REST API</td><td>Basic (email:token)</td><td>Publish Architecture, HLD, LLD, FRD, README</td></tr>
    <tr><td>GitHub REST API v3</td><td>PAT Bearer</td><td>Create PRs, poll review status for HITL gates</td></tr>
    <tr><td>Claude API</td><td>API Key (server-side)</td><td>Ticket triage, priority scoring, response suggestions</td></tr>
  </tbody>
</table>

<h3>Non-Functional Requirements</h3>
<ul>
  <li><strong>Performance:</strong> API p95 response &lt; 500ms; analytics query &lt; 1s</li>
  <li><strong>Security:</strong> All secrets via environment variables; pre-commit hook blocks hardcoded credentials; CORS restricted to localhost in dev</li>
  <li><strong>Availability:</strong> 99% uptime target (out of scope for capstone, noted for production path)</li>
  <li><strong>Testability:</strong> 100% of interactive elements have data-testid; Playwright self-healing covers selector drift</li>
</ul>
`;

const LLD_CONTENT = `
<h2>Low Level Design — AI-Enhanced CSTS</h2>
<p><em>Generated by AI Solution Architect Agent | SDLC Phase 3 — Design</em></p>

<h3>API Contracts</h3>
<table>
  <tbody>
    <tr><th>Method</th><th>Path</th><th>Request Body</th><th>Response 200</th><th>Description</th></tr>
    <tr><td>GET</td><td>/api/tickets</td><td>—</td><td>[{id, title, email, status, category, priority, sla_due_at, created_at}]</td><td>List all tickets</td></tr>
    <tr><td>POST</td><td>/api/tickets</td><td>{title, description, email}</td><td>{id, ...ticket, category, priority}</td><td>Create ticket + AI triage</td></tr>
    <tr><td>PATCH</td><td>/api/tickets/:id/status</td><td>{status: open|closed}</td><td>{id, status}</td><td>Toggle status</td></tr>
    <tr><td>GET</td><td>/api/tickets/:id/suggest-reply</td><td>—</td><td>{suggestion: string}</td><td>Get AI response draft</td></tr>
    <tr><td>PATCH</td><td>/api/tickets/:id/response</td><td>{response, accepted}</td><td>{id, response}</td><td>Save agent response</td></tr>
    <tr><td>GET</td><td>/api/analytics</td><td>—</td><td>{total, open, closed, avgResolutionMs, slaBreaches}</td><td>Dashboard metrics</td></tr>
    <tr><td>GET</td><td>/health</td><td>—</td><td>{status: ok}</td><td>Health check</td></tr>
  </tbody>
</table>

<h3>Database Schema (Enhanced)</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">sql</ac:parameter><ac:plain-text-body><![CDATA[
CREATE TABLE IF NOT EXISTS tickets (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  title       TEXT    NOT NULL,
  description TEXT    NOT NULL,
  email       TEXT    NOT NULL,
  status      TEXT    NOT NULL DEFAULT 'open',
  category    TEXT,                    -- AI triage output (Sprint 1)
  priority    TEXT DEFAULT 'medium',   -- high | medium | low (Sprint 1)
  sla_due_at  TEXT,                    -- ISO datetime (Sprint 2)
  sla_breached INTEGER DEFAULT 0,      -- 0/1 (Sprint 2)
  created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS responses (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  ticket_id   INTEGER NOT NULL REFERENCES tickets(id),
  suggestion  TEXT,
  accepted    INTEGER DEFAULT 0,       -- 0/1
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
]]></ac:plain-text-body></ac:structured-macro>

<h3>Frontend Component Tree</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
App
├── TicketForm           (data-testid: ticket-form, ticket-title, ticket-email, ticket-description, ticket-submit)
├── FilterTabs           (data-testid: filter-all, filter-open, filter-closed)
├── TicketList           (data-testid: ticket-list)
│   └── TicketItem       (data-testid: ticket-{id})
│       ├── CategoryBadge    (Sprint 1)
│       ├── PriorityBadge    (Sprint 1)
│       ├── SLACountdown     (Sprint 2)
│       └── ToggleStatus     (data-testid: toggle-status-{id})
└── Dashboard (route /dashboard)  (Sprint 3)
    ├── KPICards
    ├── TicketVolumeChart
    ├── ResolutionTimeChart
    └── SLABreachRate
]]></ac:plain-text-body></ac:structured-macro>

<h3>AI Triage Logic</h3>
<p>On POST /api/tickets, the backend calls Claude API with the ticket title and description. The prompt instructs the model to return JSON: <code>{"category": "billing|technical|general", "priority": "high|medium|low", "confidence": 0-1}</code>. The result is written to the tickets row before the API responds to the client.</p>

<h3>SLA Rules</h3>
<table>
  <tbody>
    <tr><th>Priority</th><th>SLA Window</th><th>Alert at</th></tr>
    <tr><td>High</td><td>4 hours</td><td>1 hour remaining</td></tr>
    <tr><td>Medium</td><td>8 hours</td><td>2 hours remaining</td></tr>
    <tr><td>Low</td><td>24 hours</td><td>4 hours remaining</td></tr>
  </tbody>
</table>

<h3>Error Response Contract</h3>
<p>All error responses return HTTP 4xx/5xx with body: <code>{ "error": "human-readable message" }</code>. No stack traces are exposed to the client.</p>
`;

const WIREFRAMES_CONTENT = `
<h2>Wireframes — AI-Enhanced CSTS</h2>
<p><em>Generated by AI Solution Architect Agent | SDLC Phase 3 — Design</em></p>
<p><em>Note: These are text wireframes. Visual mockups can be created in Figma or Confluence's draw.io integration.</em></p>

<h3>Screen 1: Main Ticket Dashboard</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
┌─────────────────────────────────────────────────────────────┐
│  Customer Support Ticket System                    [+ New]  │
├─────────────────────────────────────────────────────────────┤
│  [All (22)]  [Open (14)]  [Closed (8)]                      │
├─────────────────────────────────────────────────────────────┤
│  #  Title              Category   Priority  SLA    Status   │
│  ─────────────────────────────────────────────────────────  │
│  5  Login broken       Technical  🔴 High   1h 23m  Open   │
│  4  Billing question   Billing    🟡 Medium  6h 05m  Open   │
│  3  General enquiry    General    🟢 Low    22h 10m  Open   │
│  2  Password reset     Technical  🟡 Medium  ---    Closed  │
│  1  Signup issue       Technical  🔴 High   ---    Closed   │
└─────────────────────────────────────────────────────────────┘
]]></ac:plain-text-body></ac:structured-macro>

<h3>Screen 2: Submit New Ticket</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
┌─────────────────────────────────────────────────────────────┐
│  Submit a Support Ticket                                    │
├─────────────────────────────────────────────────────────────┤
│  Title *                                                    │
│  ┌───────────────────────────────────────────────────────┐  │
│  │  [ticket-title]                                       │  │
│  └───────────────────────────────────────────────────────┘  │
│  Email *                                                    │
│  ┌───────────────────────────────────────────────────────┐  │
│  │  [ticket-email]                                       │  │
│  └───────────────────────────────────────────────────────┘  │
│  Description *                                              │
│  ┌───────────────────────────────────────────────────────┐  │
│  │  [ticket-description]                                 │  │
│  │                                                       │  │
│  └───────────────────────────────────────────────────────┘  │
│                              [Submit Ticket ▶]              │
└─────────────────────────────────────────────────────────────┘
  ↓ After submit: AI assigns category + priority automatically
]]></ac:plain-text-body></ac:structured-macro>

<h3>Screen 3: Ticket Detail + AI Suggested Reply (Sprint 3)</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
┌─────────────────────────────────────────────────────────────┐
│  Ticket #5: Login broken                  🔴 High | Open   │
│  Category: Technical | SLA: 1h 23m remaining               │
├─────────────────────────────────────────────────────────────┤
│  From: user@example.com                                     │
│  "I cannot log in since this morning. Getting 401 error."  │
├─────────────────────────────────────────────────────────────┤
│  💡 AI Suggested Reply                                      │
│  ┌───────────────────────────────────────────────────────┐  │
│  │ "Hi, I'm sorry to hear you're having trouble         │  │
│  │  logging in. Please try resetting your password at   │  │
│  │  /reset-password. If the issue persists, our team    │  │
│  │  will investigate your account within 1 hour."       │  │
│  └───────────────────────────────────────────────────────┘  │
│  [✅ Accept & Send]  [✏ Edit]  [✗ Discard]                 │
└─────────────────────────────────────────────────────────────┘
]]></ac:plain-text-body></ac:structured-macro>

<h3>Screen 4: Analytics Dashboard (Sprint 3)</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
┌─────────────────────────────────────────────────────────────┐
│  Analytics Dashboard                                        │
├───────────────┬──────────────┬──────────────┬──────────────┤
│  Total: 22    │  Open: 14    │  Closed: 8   │  SLA OK: 18  │
│  Tickets      │  (63%)       │  (37%)       │  Breach: 4   │
├───────────────┴──────────────┴──────────────┴──────────────┤
│  Ticket Volume (7 days)              Avg Resolution Time   │
│  ▁▃▅▇▅▃▇                            4.2 hours             │
│  Mon Tue Wed Thu Fri Sat Sun                               │
├─────────────────────────────────────────────────────────────┤
│  Category Breakdown                                        │
│  Technical 55%  ██████████                                 │
│  Billing   27%  █████                                      │
│  General   18%  ████                                       │
└─────────────────────────────────────────────────────────────┘
]]></ac:plain-text-body></ac:structured-macro>
`;

async function run({ feedback } = {}) {
  console.log('[design] Architect Agent starting...');
  if (feedback) console.log(`[design] Incorporating feedback: ${feedback}`);

  if (!CONF_SPACE) throw new Error('CONFLUENCE_SPACE_KEY not set in .env');

  const arch = await createConfluencePage(
    'CSTS — Architecture Document (2026-07-23)',
    ARCHITECTURE_CONTENT
  );
  const hld = await createConfluencePage(
    'CSTS — High Level Design (2026-07-23)',
    HLD_CONTENT,
    arch.id
  );
  const lld = await createConfluencePage(
    'CSTS — Low Level Design (2026-07-23)',
    LLD_CONTENT,
    arch.id
  );
  const wireframes = await createConfluencePage(
    'CSTS — Wireframes (2026-07-23)',
    WIREFRAMES_CONTENT,
    arch.id
  );

  console.log(`\n[design] All 4 artifacts published to Confluence.`);
  console.log(`[design] HITL REVIEW REQUIRED — Review design docs in Confluence.`);
  console.log(`[design] Base URL: ${CONF_BASE}/spaces/${CONF_SPACE}`);

  return {
    architecture: arch.id,
    hld: hld.id,
    lld: lld.id,
    wireframes: wireframes.id,
    confluenceUrl: CONF_BASE + arch._links?.webui,
  };
}

module.exports = { run };

if (require.main === module) {
  run().catch(err => {
    console.error('[design] Failed:', err.message);
    process.exit(1);
  });
}
