require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const { execSync } = require('child_process');
const { createPR } = require('../hitl/reviewer');

/**
 * Development Phase Agent (Dev Persona)
 * - Triggers Claude Code CLI via CodeMie to generate enhancements
 * - Commits code to a feature branch
 * - Opens a GitHub PR for HITL review
 */

const OWNER = process.env.GITHUB_OWNER;
const REPO = process.env.GITHUB_REPO;

function git(cmd, cwd) {
  return execSync(`git ${cmd}`, { cwd, encoding: 'utf8', stdio: 'pipe' }).trim();
}

async function run({ feedback } = {}) {
  console.log('[development] Dev Agent starting...');
  if (feedback) console.log(`[development] Incorporating feedback: ${feedback}`);

  const repoPath = require('path').join(__dirname, '../..');
  const branch = `feature/ai-enhancements-${Date.now()}`;

  // Create feature branch
  try {
    git(`checkout -b ${branch}`, repoPath);
    console.log(`[development] Created branch: ${branch}`);
  } catch (err) {
    throw new Error(`Failed to create branch: ${err.message}`);
  }

  // Placeholder: in a real run, Claude Code CLI via CodeMie would be invoked here
  // e.g.: execSync(`claude "Implement AI triage endpoint as per LLD" --yes`, { cwd: repoPath })
  console.log('[development] Claude Code CLI would run here via CodeMie to generate enhancements.');
  console.log('[development] Code generated. Staging and committing...');

  git('add .', repoPath);

  try {
    git('commit -m "feat: AI-driven enhancements — triage, priority, SLA, analytics"', repoPath);
  } catch {
    console.log('[development] Nothing new to commit (already up to date).');
  }

  // Push branch and open PR
  try {
    git(`push origin ${branch}`, repoPath);
  } catch (err) {
    throw new Error(`Failed to push branch: ${err.message}`);
  }

  const pr = await createPR({
    branch,
    title: `feat: AI-driven enhancements for Customer Support Ticket System`,
    body: `## Summary\n- AI triage and categorisation\n- Priority/severity scoring\n- SLA tracking\n- Analytics dashboard\n- Auto-response suggestions\n\n${feedback ? `## HITL Feedback Addressed\n${feedback}` : ''}\n\n> Generated by Dev Agent via Claude Code CLI (CodeMie)`,
    base: 'main',
  });

  return { prUrl: pr.html_url, prNumber: pr.number, branch };
}

module.exports = { run };

if (require.main === module) {
  run().catch(err => { console.error('[development] Failed:', err.message); process.exit(1); });
}
