require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const fs = require('fs');
const path = require('path');
const https = require('https');
const { commitFile, fileUrl } = require('../integrations/github');

/**
 * Documentation Phase Agent (Tech Writer Persona)
 * - Publishes FRD, Architecture, HLD, LLD, Wireframes to Confluence
 * - Commits README.md to the feature branch (codebase artifact)
 */

const CONF_BASE  = process.env.CONFLUENCE_BASE_URL;
const CONF_SPACE = process.env.CONFLUENCE_SPACE_KEY;
const JIRA_EMAIL = process.env.JIRA_EMAIL;
const JIRA_TOKEN = process.env.JIRA_API_TOKEN;

function confluenceRequest(method, path, body = null) {
  return new Promise((resolve, reject) => {
    const auth = Buffer.from(`${JIRA_EMAIL}:${JIRA_TOKEN}`).toString('base64');
    const url = new URL(CONF_BASE + path);
    const b = body ? JSON.stringify(body) : null;
    const req = https.request({
      hostname: url.hostname,
      path: url.pathname + url.search,
      method,
      headers: {
        'Authorization': `Basic ${auth}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        ...(b ? { 'Content-Length': Buffer.byteLength(b) } : {}),
      },
    }, (res) => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => {
        try { resolve({ status: res.statusCode, body: JSON.parse(data) }); }
        catch { resolve({ status: res.statusCode, body: data }); }
      });
    });
    req.on('error', reject);
    if (b) req.write(b);
    req.end();
  });
}

async function findPage(title) {
  const encoded = encodeURIComponent(title);
  const res = await confluenceRequest('GET', `/rest/api/content?title=${encoded}&spaceKey=${CONF_SPACE}&expand=version`);
  if (res.status === 200 && res.body.results?.length > 0) return res.body.results[0];
  return null;
}

async function createConfluencePage(title, content, parentId = null) {
  const existing = await findPage(title);

  if (existing) {
    const nextVersion = existing.version.number + 1;
    const updateBody = {
      type: 'page',
      title,
      version: { number: nextVersion },
      body: { storage: { value: content, representation: 'storage' } },
      ...(parentId ? { ancestors: [{ id: parentId }] } : {}),
    };
    const res = await confluenceRequest('PUT', `/rest/api/content/${existing.id}`, updateBody);
    if (res.status !== 200) {
      throw new Error(`Confluence page update failed (${res.status}): ${JSON.stringify(res.body)}`);
    }
    const link = CONF_BASE + res.body._links?.webui;
    console.log(`[documentation] Updated: "${title}" → ${link}`);
    return res.body;
  }

  const body = {
    type: 'page',
    title,
    space: { key: CONF_SPACE },
    body: { storage: { value: content, representation: 'storage' } },
    ...(parentId ? { ancestors: [{ id: parentId }] } : {}),
  };
  const res = await confluenceRequest('POST', '/rest/api/content', body);
  if (res.status !== 200 && res.status !== 201) {
    throw new Error(`Confluence page creation failed (${res.status}): ${JSON.stringify(res.body)}`);
  }
  const link = CONF_BASE + res.body._links?.webui;
  console.log(`[documentation] Published: "${title}" → ${link}`);
  return res.body;
}

// ─── Architecture content ─────────────────────────────────────────────────────

const ARCHITECTURE_CONTENT = `
<h2>System Architecture — AI-Enhanced Customer Support Ticket System</h2>
<p><em>Generated by Documentation Agent | SDLC Phase 6 — Documentation | mm-learning-group-1</em></p>

<h3>Overview</h3>
<p>Three-tier architecture: React 18 SPA → Node.js 24 / Express 4 REST API → SQLite (<code>node:sqlite</code> built-in). An AI layer powered by Claude API provides ticket triage, priority scoring, and auto-response drafts.</p>

<h3>Component Map</h3>
<table>
  <tbody>
    <tr><th>Component</th><th>Technology</th><th>Responsibility</th></tr>
    <tr><td>Frontend</td><td>React 18</td><td>Ticket form, list view, analytics dashboard, filter tabs</td></tr>
    <tr><td>Backend API</td><td>Node.js 24 / Express 4</td><td>REST endpoints, business logic, AI integration, SLA enforcement</td></tr>
    <tr><td>Database</td><td>SQLite — node:sqlite built-in</td><td>Ticket storage, response history, SLA records</td></tr>
    <tr><td>AI Layer</td><td>Claude API via Anthropic SDK</td><td>Triage, priority scoring, reply drafts</td></tr>
    <tr><td>Testing</td><td>Playwright</td><td>E2E tests with self-healing selector repair</td></tr>
    <tr><td>CI/CD</td><td>GitHub Actions</td><td>Build, test, artifact packaging on every push to main</td></tr>
  </tbody>
</table>

<h3>Architecture Diagram</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
┌──────────────────────────────────────────────────────────┐
│                      BROWSER                             │
│  React 18 SPA (port 3000)                                │
│  TicketForm | TicketList | Dashboard | FilterTabs        │
└─────────────────────┬────────────────────────────────────┘
                      │ REST (fetch /api/*)
┌─────────────────────▼────────────────────────────────────┐
│          Node.js 24 / Express 4 (port 3001)              │
│  /api/tickets  /api/tickets/:id/suggest-reply            │
│  /api/analytics /health                                  │
│          ┌─────────────────────────┐                     │
│          │  AI Services (Claude)   │                     │
│          │  triage / scoring       │                     │
│          │  auto-response drafts   │                     │
│          └───────────┬─────────────┘                     │
└──────────────────────┼───────────────────────────────────┘
                       │
┌──────────────────────▼───────────────────────────────────┐
│         SQLite (node:sqlite built-in)                    │
│  tickets | responses                                     │
└──────────────────────────────────────────────────────────┘
]]></ac:plain-text-body></ac:structured-macro>

<h3>Key Design Decisions</h3>
<ul>
  <li><strong>node:sqlite over better-sqlite3:</strong> Node v24 built-in — no C++ compilation, no Visual Studio dependency.</li>
  <li><strong>REST over GraphQL:</strong> Simpler toolchain; CRUD + analytics endpoints are sufficient at this scale.</li>
  <li><strong>Claude API server-side only:</strong> API keys never exposed to the browser.</li>
  <li><strong>data-testid on all interactive elements:</strong> Stable Playwright targets with self-healing fallback.</li>
  <li><strong>File-based SQLite:</strong> Zero ops overhead for capstone; trivially replaced with PostgreSQL for production.</li>
</ul>
`.trim();

// ─── HLD content ──────────────────────────────────────────────────────────────

const HLD_CONTENT = `
<h2>High Level Design — AI-Enhanced CSTS</h2>
<p><em>Generated by Documentation Agent | SDLC Phase 6 — Documentation</em></p>

<h3>Data Flow</h3>
<ol>
  <li>User submits ticket via React form → POST /api/tickets</li>
  <li>Express API validates and persists to SQLite</li>
  <li>AI triage service (Claude API) assigns category and priority score</li>
  <li>SLA timer starts: High = 4 h, Medium = 8 h, Low = 24 h</li>
  <li>Agent views AI-suggested reply in the ticket detail panel</li>
  <li>Analytics dashboard aggregates ticket volume, resolution time, SLA breach rate</li>
</ol>

<h3>Sprint-to-Component Mapping</h3>
<table>
  <tbody>
    <tr><th>Sprint</th><th>Features</th><th>New Components</th><th>New DB Fields</th></tr>
    <tr><td>Sprint 1</td><td>AI Triage, Priority Scoring</td><td>CategoryBadge, PriorityBadge</td><td>category, priority</td></tr>
    <tr><td>Sprint 2</td><td>SLA Tracking</td><td>SLACountdown, AlertBanner</td><td>sla_due_at, sla_breached</td></tr>
    <tr><td>Sprint 3</td><td>Auto-Response, Analytics</td><td>SuggestedReply, Dashboard, Charts</td><td>responses table</td></tr>
  </tbody>
</table>

<h3>Integration Points</h3>
<table>
  <tbody>
    <tr><th>Integration</th><th>Auth</th><th>Usage</th></tr>
    <tr><td>JIRA REST API v3</td><td>Basic (email:token)</td><td>Create EPICs, Stories, Tasks</td></tr>
    <tr><td>Confluence REST API</td><td>Basic (email:token)</td><td>Publish Architecture, HLD, LLD, Wireframes, FRD</td></tr>
    <tr><td>GitHub REST API v3</td><td>PAT Bearer</td><td>Create PRs, poll reviews, commit README</td></tr>
    <tr><td>GitLab REST API v4</td><td>PAT</td><td>Wiki, milestones, issues, MR for project plan</td></tr>
    <tr><td>Claude API</td><td>API Key (server-side)</td><td>Triage, priority scoring, response suggestions</td></tr>
  </tbody>
</table>
`.trim();

// ─── LLD content ──────────────────────────────────────────────────────────────

const LLD_CONTENT = `
<h2>Low Level Design — AI-Enhanced CSTS</h2>
<p><em>Generated by Documentation Agent | SDLC Phase 6 — Documentation</em></p>

<h3>API Contracts</h3>
<table>
  <tbody>
    <tr><th>Method</th><th>Path</th><th>Request Body</th><th>Response 200</th></tr>
    <tr><td>GET</td><td>/api/tickets</td><td>—</td><td>[{id, title, email, status, category, priority, sla_due_at}]</td></tr>
    <tr><td>POST</td><td>/api/tickets</td><td>{title, description, email}</td><td>{id, ...ticket, category, priority}</td></tr>
    <tr><td>PATCH</td><td>/api/tickets/:id/status</td><td>{status}</td><td>{id, status}</td></tr>
    <tr><td>GET</td><td>/api/tickets/:id/suggest-reply</td><td>—</td><td>{suggestion: string}</td></tr>
    <tr><td>PATCH</td><td>/api/tickets/:id/response</td><td>{response, accepted}</td><td>{id, response}</td></tr>
    <tr><td>GET</td><td>/api/analytics</td><td>—</td><td>{total, open, closed, avgResolutionMs, slaBreaches}</td></tr>
    <tr><td>GET</td><td>/health</td><td>—</td><td>{status: ok}</td></tr>
  </tbody>
</table>

<h3>Database Schema</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">sql</ac:parameter><ac:plain-text-body><![CDATA[
CREATE TABLE IF NOT EXISTS tickets (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  title        TEXT    NOT NULL,
  description  TEXT    NOT NULL,
  email        TEXT    NOT NULL,
  status       TEXT    NOT NULL DEFAULT 'open',
  category     TEXT,                    -- AI triage (Sprint 1)
  priority     TEXT    DEFAULT 'medium',-- high | medium | low
  sla_due_at   TEXT,                    -- ISO datetime (Sprint 2)
  sla_breached INTEGER DEFAULT 0,
  created_at   TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at   TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS responses (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  ticket_id  INTEGER NOT NULL REFERENCES tickets(id),
  suggestion TEXT,
  accepted   INTEGER DEFAULT 0,
  created_at TEXT    NOT NULL DEFAULT (datetime('now'))
);
]]></ac:plain-text-body></ac:structured-macro>

<h3>Frontend Component Tree</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
App
├── TicketForm        (data-testid: ticket-form, ticket-title, ticket-email, ticket-description, ticket-submit)
├── FilterTabs        (data-testid: filter-all, filter-open, filter-closed)
├── TicketList        (data-testid: ticket-list)
│   └── TicketItem    (data-testid: ticket-{id})
│       ├── CategoryBadge   (Sprint 1)
│       ├── PriorityBadge   (Sprint 1)
│       ├── SLACountdown    (Sprint 2)
│       └── ToggleStatus    (data-testid: toggle-status-{id})
└── Dashboard (/dashboard)  (Sprint 3)
    ├── KPICards
    ├── TicketVolumeChart
    ├── ResolutionTimeChart
    └── SLABreachRate
]]></ac:plain-text-body></ac:structured-macro>

<h3>Error Response Contract</h3>
<p>All error responses return HTTP 4xx/5xx with <code>{ "error": "human-readable message" }</code>. No stack traces exposed to clients.</p>
`.trim();

// ─── Wireframes content ───────────────────────────────────────────────────────

const WIREFRAMES_CONTENT = `
<h2>Wireframes — AI-Enhanced CSTS</h2>
<p><em>Generated by Documentation Agent | SDLC Phase 6 — Documentation</em></p>
<p><em>Text wireframes. Visual mockups can be created in Figma or Confluence draw.io.</em></p>

<h3>Screen 1 — Main Ticket List</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
┌─────────────────────────────────────────────────────────────┐
│  Customer Support Ticket System                    [+ New]  │
├─────────────────────────────────────────────────────────────┤
│  [All (22)]  [Open (14)]  [Closed (8)]                      │
├─────────────────────────────────────────────────────────────┤
│  #   Title              Category   Priority  SLA    Status  │
│   5  Login broken       Technical  🔴 High   1h 23m  Open  │
│   4  Billing question   Billing    🟡 Medium  6h 05m  Open  │
│   3  General enquiry    General    🟢 Low    22h 10m  Open  │
│   2  Password reset     Technical  🟡 Medium  ---   Closed  │
└─────────────────────────────────────────────────────────────┘
]]></ac:plain-text-body></ac:structured-macro>

<h3>Screen 2 — Submit Ticket</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
┌─────────────────────────────────────────────────────────────┐
│  Submit a Support Ticket                                    │
│  Title * ──────────────────────────────────────────────── │
│  Email * ──────────────────────────────────────────────── │
│  Description * ─────────────────────────────────────────── │
│                                                             │
│                              [Submit Ticket ▶]              │
└─────────────────────────────────────────────────────────────┘
  ↓ On submit: AI auto-assigns category + priority
]]></ac:plain-text-body></ac:structured-macro>

<h3>Screen 3 — Ticket Detail + AI Suggested Reply</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
┌─────────────────────────────────────────────────────────────┐
│  Ticket #5: Login broken                  🔴 High | Open   │
│  Category: Technical | SLA: 1h 23m remaining               │
│  From: user@example.com                                     │
│  "I cannot log in since this morning. Getting 401 error."  │
├─────────────────────────────────────────────────────────────┤
│  💡 AI Suggested Reply                                      │
│  "Hi, sorry to hear you're having trouble logging in.       │
│   Please try resetting your password at /reset-password."  │
│  [✅ Accept & Send]  [✏ Edit]  [✗ Discard]                 │
└─────────────────────────────────────────────────────────────┘
]]></ac:plain-text-body></ac:structured-macro>

<h3>Screen 4 — Analytics Dashboard</h3>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
┌─────────────────────────────────────────────────────────────┐
│  Analytics Dashboard                                        │
├──────────────┬─────────────┬─────────────┬─────────────────┤
│  Total: 22   │  Open: 14   │  Closed: 8  │  SLA Breach: 4  │
│  Avg: 4.2h   │             │             │                 │
├──────────────┴─────────────┴─────────────┴─────────────────┤
│  Ticket Volume (7 days)           Category Breakdown        │
│  ▁▃▅▇▅▃▇                         Technical 55% ██████████  │
│  Mon Tue Wed Thu Fri Sat Sun      Billing   27% █████       │
│                                   General   18% ████        │
└─────────────────────────────────────────────────────────────┘
]]></ac:plain-text-body></ac:structured-macro>
`.trim();

// ─── README content (built dynamically using pipeline state) ──────────────────

function buildReadmeContent(state) {
  const ghOwner = process.env.GITHUB_OWNER || 'SubhasriGit';
  const ghRepo  = process.env.GITHUB_REPO  || 'Customer-Support-Ticket-System';
  const dev     = state?.phaseOutputs?.development || {};
  const prRef   = dev.prUrl ? ` ([PR #${dev.prNumber}](${dev.prUrl}))` : '';

  return `# Customer Support Ticket System (CSTS)${prRef}

AI-Enhanced Customer Support platform built as part of the **mm-learning-group-1 capstone** — demonstrating AI-driven SDLC orchestration with CodeMie assistants, HITL gates, and self-healing automation.

## Features

| Feature | Sprint | Status |
|---|---|---|
| Submit and track support tickets | Base | ✅ |
| AI-powered ticket triage (category + priority) | Sprint 1 | ✅ |
| Priority and severity scoring with badges | Sprint 1 | ✅ |
| SLA tracking and breach alerts | Sprint 2 | ✅ |
| Analytics dashboard (KPI cards + charts) | Sprint 3 | ✅ |
| AI auto-response suggestions | Sprint 3 | ✅ |

## Tech Stack

| Layer | Technology |
|---|---|
| Frontend | React 18 |
| Backend | Node.js 24 / Express 4 |
| Database | SQLite via \`node:sqlite\` (built-in — no native compilation) |
| AI | Claude API (Anthropic SDK) |
| Testing | Playwright with self-healing selectors |
| CI/CD | GitHub Actions |

## Prerequisites

- Node.js >= 24
- npm >= 10

## Setup

\`\`\`bash
git clone https://github.com/${ghOwner}/${ghRepo}.git
cd ${ghRepo}
cp .env.example .env   # fill in credentials
npm run setup:hooks    # install pre-commit secret-detection hook
cd backend && npm install && cd ..
cd frontend && npm install && cd ..
\`\`\`

## Environment Variables

| Variable | Description |
|---|---|
| \`GITHUB_PAT\` | GitHub personal access token |
| \`JIRA_BASE_URL\` | Atlassian JIRA base URL |
| \`JIRA_EMAIL\` | Atlassian account email |
| \`JIRA_API_TOKEN\` | JIRA API token |
| \`CONFLUENCE_BASE_URL\` | Confluence base URL |
| \`CONFLUENCE_SPACE_KEY\` | Confluence space key |
| \`GITLAB_PAT\` | GitLab personal access token |
| \`GITLAB_PROJECT_ID\` | GitLab project ID |
| \`PORT\` | Backend port (default: 3001) |

## Run

\`\`\`bash
# Backend (port 3001)
cd backend && npm start

# Frontend (port 3000) — new terminal
cd frontend && npm start
\`\`\`

Open http://localhost:3000

## Run Tests

\`\`\`bash
cd tests && npm install
npx playwright install chromium
npx playwright test
npx playwright show-report
\`\`\`

## SDLC Pipeline

\`\`\`bash
# Full 8-phase pipeline
npm run workflow

# Start from a specific phase
node workflow/orchestrator.js development

# Single phase
node workflow/orchestrator.js documentation
\`\`\`

Set \`HITL_AUTO_APPROVE=true\` to bypass all human-in-the-loop gates.

## API Reference

| Method | Path | Description |
|---|---|---|
| GET | /api/tickets | List all tickets |
| POST | /api/tickets | Create ticket + AI triage |
| PATCH | /api/tickets/:id/status | Toggle open / closed |
| GET | /api/tickets/:id/suggest-reply | AI reply suggestion |
| PATCH | /api/tickets/:id/response | Save agent response |
| GET | /api/analytics | Dashboard metrics |
| GET | /health | Health check |

## Project Structure

\`\`\`
├── frontend/src/              React 18 application
├── backend/
│   ├── routes/tickets.js      Ticket CRUD + AI routes
│   ├── db/database.js         SQLite connection
│   └── services/ai.js         Claude API integration
├── tests/e2e/                 Playwright specs
├── workflow/
│   ├── orchestrator.js        SDLC pipeline orchestrator
│   ├── phases/                Per-phase agent runners
│   ├── hitl/                  Human-in-the-loop reviewer
│   ├── integrations/          GitHub, GitLab, code-review helpers
│   └── report/                RunDetails generator
└── .claude/agents/            CodeMie agent definitions
\`\`\`

## Security

- The pre-commit hook blocks hardcoded API keys before commit.
- All credentials are stored in \`.env\` (gitignored).
- Never commit the \`.env\` file.

---

*Generated by CSTS Documentation Agent — AI-Driven SDLC Pipeline | mm-learning-group-1*
`.trim();
}

// ─── README content (static fallback kept for backward-compat) ───────────────

const README_CONTENT = `# Customer Support Ticket System

AI-Enhanced Customer Support platform built as part of the **mm-learning-group-1 capstone** — demonstrating AI-driven SDLC orchestration with CodeMie assistants, HITL gates, and self-healing automation.

## Features

| Feature | Sprint | Status |
|---------|--------|--------|
| Submit and track support tickets | Base | ✅ |
| AI-powered ticket triage (category + priority) | Sprint 1 | ✅ |
| Priority and severity scoring with badges | Sprint 1 | ✅ |
| SLA tracking and breach alerts | Sprint 2 | ✅ |
| Analytics dashboard (KPI cards + charts) | Sprint 3 | ✅ |
| AI auto-response suggestions | Sprint 3 | ✅ |

## Tech Stack

| Layer | Technology |
|---|---|
| Frontend | React 18 |
| Backend | Node.js 24 / Express 4 |
| Database | SQLite via \`node:sqlite\` (built-in, no native compilation) |
| Testing | Playwright with self-healing selectors |
| Build | npm scripts |
| AI | Claude API (via CodeMie MCP) with keyword fallback |

## Prerequisites

- Node.js >= 22.5 (uses built-in \`node:sqlite\`)
- npm >= 9

## Setup

\`\`\`bash
# 1. Clone and configure environment
cp .env.example .env
# Edit .env and fill in: JIRA_API_TOKEN, GITHUB_PAT, CONFLUENCE_SPACE_KEY, ANTHROPIC_API_KEY

# 2. Install pre-commit hook (blocks hardcoded secrets)
npm run setup:hooks

# 3. Install dependencies
cd backend && npm install && cd ..
cd frontend && npm install && cd ..
\`\`\`

## Run

\`\`\`bash
# Backend (port 3001)
cd backend && npm start

# Frontend (port 3000) — new terminal
cd frontend && npm start
\`\`\`

Open http://localhost:3000

## Run Tests

\`\`\`bash
cd tests
npm install
npx playwright install chromium
npx playwright test
npx playwright show-report   # view HTML report
\`\`\`

## Run SDLC Workflow

Each phase can be triggered individually after the previous HITL gate is approved:

\`\`\`bash
node workflow/phases/analysis.js      # BA: create JIRA EPICs/Stories/Tasks
node workflow/phases/plan.js          # Planner: sprint plan + JIRA updates
node workflow/phases/design.js        # Architect: publish to Confluence
node workflow/phases/documentation.js # Tech Writer: README + FRD
node workflow/phases/build.js         # DevOps: build artifact
\`\`\`

Or run the full pipeline from any phase:
\`\`\`bash
node workflow/orchestrator.js [analysis|plan|design|development|documentation|build]
\`\`\`

## Project Structure

\`\`\`
├── frontend/                  React 18 application
│   └── src/
│       ├── components/        TicketForm, TicketList, Dashboard, SuggestedReply
│       └── services/api.js    REST client
├── backend/                   Express 4 API
│   ├── db/
│   │   ├── database.js        Migration runner (node:sqlite)
│   │   └── migrations/        001-004 versioned SQL migrations
│   ├── routes/                tickets, analytics, suggestions
│   └── services/              triageService (Claude API + keyword fallback)
├── workflow/                  AI-driven SDLC pipeline
│   ├── phases/                analysis, plan, design, development, documentation, build
│   ├── hooks/                 pre-phase, post-phase, on-failure (retry + backoff)
│   ├── hitl/                  GitHub PR-based HITL reviewer
│   └── self-healing/          Playwright selector healer
├── tests/
│   └── specs/tickets.spec.js  Playwright E2E with resilient locators
├── scripts/setup-hooks.js     Cross-platform pre-commit hook installer
└── .github/hooks/pre-commit   Secret detection hook
\`\`\`

## Security

- The pre-commit hook blocks any hardcoded API keys, tokens, or passwords before commit.
- All credentials are stored in \`.env\` (gitignored). Never commit the \`.env\` file.
- The \`.env.example\` file contains only placeholder values and is safe to commit.

## Contributing

1. Create a feature branch: \`git checkout -b feature/your-feature\`
2. Run the SDLC pipeline agents for analysis and planning
3. Submit a PR — the HITL reviewer will request human approval before merge

---

*Generated by AI Tech Writer Agent — SDLC Phase 5 (Documentation) | mm-learning-group-1*
`;

// ─── FRD content ──────────────────────────────────────────────────────────────

const FRD_CONTENT = `
<h2>Functional Requirements Document — AI-Enhanced Customer Support Ticket System</h2>
<p><em>Generated by AI Tech Writer Agent | SDLC Phase 5 — Documentation | mm-learning-group-1 | 2026-07-23</em></p>

<h3>1. Purpose and Scope</h3>
<p>This document defines the functional requirements for the AI-Enhanced Customer Support Ticket System (CSTS). The system provides a web-based interface for customers to submit support tickets and for support agents to manage, triage, and resolve them. AI capabilities are layered on top of the base application across three sprints.</p>

<h3>2. Stakeholders</h3>
<table>
  <tbody>
    <tr><th>Role</th><th>Responsibilities</th></tr>
    <tr><td>Customer</td><td>Submit support tickets; receive responses</td></tr>
    <tr><td>Support Agent</td><td>View, triage, respond to, and close tickets</td></tr>
    <tr><td>Support Manager</td><td>Monitor analytics dashboard; track SLA compliance</td></tr>
    <tr><td>Developer / DevOps</td><td>Deploy and maintain the system</td></tr>
  </tbody>
</table>

<h3>3. Functional Requirements</h3>

<h4>FR-01: Ticket Submission</h4>
<p><strong>Description:</strong> The system shall allow customers to submit support tickets via a web form.</p>
<p><strong>Priority:</strong> High | <strong>Story:</strong> Base</p>
<p><strong>Acceptance Criteria:</strong></p>
<ul>
  <li>Form fields: Title (required), Email (required), Description (required)</li>
  <li>All fields validated; errors shown inline</li>
  <li>On submit: ticket created, triage runs, ticket appears in list</li>
</ul>

<h4>FR-02: AI Ticket Triage (KAN-3)</h4>
<p><strong>Description:</strong> The system shall automatically assign a category and priority to every new ticket using AI.</p>
<p><strong>Priority:</strong> High | <strong>Story Points:</strong> 8 | <strong>Sprint:</strong> 1</p>
<p><strong>Acceptance Criteria:</strong></p>
<ul>
  <li>Category assigned: <code>technical</code> | <code>billing</code> | <code>general</code></li>
  <li>Priority assigned: <code>high</code> | <code>medium</code> | <code>low</code></li>
  <li>Claude API used when ANTHROPIC_API_KEY configured; keyword matching as fallback</li>
  <li>Category and priority badges visible on ticket cards</li>
</ul>

<h4>FR-03: Priority and Severity Scoring (KAN-7)</h4>
<p><strong>Description:</strong> Tickets shall be visually differentiated by priority using colour-coded badges.</p>
<p><strong>Priority:</strong> High | <strong>Story Points:</strong> 5 | <strong>Sprint:</strong> 1</p>
<p><strong>Acceptance Criteria:</strong></p>
<ul>
  <li>High priority: red badge</li>
  <li>Medium priority: yellow badge</li>
  <li>Low priority: green badge</li>
  <li>Ticket list sortable/filterable by status</li>
</ul>

<h4>FR-04: SLA Tracking and Breach Alerts (KAN-11)</h4>
<p><strong>Description:</strong> The system shall enforce SLA deadlines per priority and display a live countdown.</p>
<p><strong>Priority:</strong> High | <strong>Story Points:</strong> 8 | <strong>Sprint:</strong> 2</p>
<p><strong>Acceptance Criteria:</strong></p>
<ul>
  <li>SLA windows: High = 4h, Medium = 8h, Low = 24h</li>
  <li>Countdown timer displayed on each open ticket card</li>
  <li>Countdown turns red when &lt; 1 hour remaining</li>
  <li><code>sla_breached</code> flag set when SLA window expires and ticket still open</li>
  <li>"SLA Breached" badge shown in place of countdown after breach</li>
</ul>

<h4>FR-05: Auto-Response Suggestions (KAN-19)</h4>
<p><strong>Description:</strong> The system shall suggest AI-generated reply templates for support agents.</p>
<p><strong>Priority:</strong> Medium | <strong>Story Points:</strong> 13 | <strong>Sprint:</strong> 3</p>
<p><strong>Acceptance Criteria:</strong></p>
<ul>
  <li>"💡 Suggest Reply" button appears on open ticket cards</li>
  <li>AI-generated reply pre-populated in editable textarea</li>
  <li>Agent can accept, edit, or discard the suggestion</li>
  <li>Accepted/saved responses recorded in <code>responses</code> table</li>
</ul>

<h4>FR-06: Analytics Dashboard (KAN-15)</h4>
<p><strong>Description:</strong> The system shall provide a dashboard summarising ticket volume and performance metrics.</p>
<p><strong>Priority:</strong> Medium | <strong>Story Points:</strong> 8 | <strong>Sprint:</strong> 3</p>
<p><strong>Acceptance Criteria:</strong></p>
<ul>
  <li>KPI cards: Total, Open, Closed, SLA Breaches, Avg Resolution Time</li>
  <li>Bar charts: by category, by priority, volume over last 7 days</li>
  <li>Dashboard accessible via "Analytics" tab in top nav</li>
</ul>

<h3>4. Non-Functional Requirements</h3>
<ul>
  <li><strong>Performance:</strong> API p95 response &lt; 500ms; analytics query &lt; 1s</li>
  <li><strong>Security:</strong> No secrets in code; pre-commit hook enforced; HTTPS in production</li>
  <li><strong>Testability:</strong> All interactive elements have <code>data-testid</code>; Playwright self-healing covers selector drift</li>
  <li><strong>Portability:</strong> SQLite via Node built-in — no C++ build tools required</li>
</ul>

<h3>5. Out of Scope</h3>
<ul>
  <li>Email notification delivery (SLA alerts are visual-only in this release)</li>
  <li>User authentication and role-based access control</li>
  <li>Multi-tenant support</li>
  <li>Production deployment and hosting</li>
</ul>

<h3>6. Glossary</h3>
<table>
  <tbody>
    <tr><th>Term</th><th>Definition</th></tr>
    <tr><td>CSTS</td><td>Customer Support Ticket System</td></tr>
    <tr><td>HITL</td><td>Human-in-the-Loop — manual approval gate between SDLC phases</td></tr>
    <tr><td>SLA</td><td>Service Level Agreement — maximum response time per priority</td></tr>
    <tr><td>Triage</td><td>Automatic classification of a ticket's category and priority by AI</td></tr>
    <tr><td>CodeMie</td><td>EPAM AI platform providing Claude Code CLI and MCP integration</td></tr>
  </tbody>
</table>
`;

// ─── API docs content ─────────────────────────────────────────────────────────

const API_DOCS_CONTENT = `
<h2>API Documentation — Customer Support Ticket System</h2>
<p><em>Generated by AI Tech Writer Agent | 2026-07-23</em></p>
<p>Base URL: <code>http://localhost:3001</code></p>

<h3>Authentication</h3>
<p>No authentication required (development scope). Add Bearer token middleware before production deployment.</p>

<h3>Endpoints</h3>

<h4>GET /health</h4>
<p>Health check.</p>
<p><strong>Response 200:</strong> <code>{ "status": "ok" }</code></p>

<h4>GET /api/tickets</h4>
<p>List all tickets ordered by creation date descending. SLA breach flags are updated inline.</p>
<p><strong>Response 200:</strong> Array of ticket objects.</p>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">json</ac:parameter><ac:plain-text-body><![CDATA[
[{
  "id": 1, "title": "Login broken", "description": "...", "email": "user@example.com",
  "status": "open", "category": "technical", "priority": "high",
  "sla_due_at": "2026-07-23T14:22:05.573Z", "sla_breached": 0,
  "created_at": "2026-07-23 10:22:05", "updated_at": "2026-07-23 10:22:05"
}]
]]></ac:plain-text-body></ac:structured-macro>

<h4>POST /api/tickets</h4>
<p>Create a ticket. AI triage (category + priority) and SLA deadline are set automatically.</p>
<p><strong>Request Body:</strong></p>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">json</ac:parameter><ac:plain-text-body><![CDATA[{ "title": "string (required)", "description": "string (required)", "email": "string (required)" }]]></ac:plain-text-body></ac:structured-macro>
<p><strong>Response 201:</strong> Created ticket object (includes category, priority, sla_due_at).</p>
<p><strong>Response 400:</strong> <code>{ "error": "title, description, and email are required" }</code></p>

<h4>PATCH /api/tickets/:id/status</h4>
<p>Toggle ticket status.</p>
<p><strong>Request Body:</strong> <code>{ "status": "open" | "closed" }</code></p>
<p><strong>Response 200:</strong> Updated ticket object.</p>
<p><strong>Response 404:</strong> <code>{ "error": "Ticket not found" }</code></p>

<h4>GET /api/tickets/:id/suggest-reply</h4>
<p>Get an AI-generated reply suggestion for a ticket. Uses Claude API if configured, falls back to template.</p>
<p><strong>Response 200:</strong> <code>{ "suggestion": "string" }</code></p>

<h4>PATCH /api/tickets/:id/response</h4>
<p>Save agent response (accepted or discarded suggestion).</p>
<p><strong>Request Body:</strong> <code>{ "response": "string (required)", "accepted": boolean }</code></p>
<p><strong>Response 200:</strong> <code>{ "id": number, "response": "string", "accepted": boolean }</code></p>

<h4>GET /api/analytics</h4>
<p>Aggregated metrics for the dashboard.</p>
<p><strong>Response 200:</strong></p>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">json</ac:parameter><ac:plain-text-body><![CDATA[
{
  "total": 22, "open": 14, "closed": 8, "slaBreaches": 3,
  "avgResolutionMs": 15120000,
  "byCategory": [{ "category": "technical", "count": 12 }],
  "byPriority": [{ "priority": "high", "count": 7 }],
  "volumeByDay": [{ "day": "2026-07-23", "count": 5 }]
}
]]></ac:plain-text-body></ac:structured-macro>
`;

async function run({ feedback, state } = {}) {
  console.log('[documentation] Tech Writer Agent starting...');
  if (feedback) console.log(`[documentation] Incorporating feedback: ${feedback}`);

  const devOutput    = state?.phaseOutputs?.development || {};
  const featureBranch = devOutput.branch;            // branch opened by development phase
  const targetBranch  = featureBranch || 'main';
  const warnings = [];

  // ── Step 1: Architecture → Confluence ─────────────────────────────────────
  console.log('[documentation] Step 1/5 — Publishing Architecture to Confluence...');
  let archPage;
  try {
    archPage = await createConfluencePage('CSTS — Architecture Document', ARCHITECTURE_CONTENT);
    console.log(`[documentation] Architecture → ${CONF_BASE + archPage._links?.webui}`);
  } catch (err) {
    warnings.push(`Architecture: ${err.message}`);
    console.warn(`[documentation] Architecture failed (non-fatal): ${err.message}`);
  }

  // ── Step 2: HLD + LLD + Wireframes as children of Architecture ────────────
  console.log('[documentation] Step 2/5 — Publishing HLD, LLD, Wireframes...');
  let hldPage, lldPage, wfPage;
  try {
    hldPage = await createConfluencePage('CSTS — High Level Design (HLD)', HLD_CONTENT, archPage?.id);
    lldPage = await createConfluencePage('CSTS — Low Level Design (LLD)', LLD_CONTENT, archPage?.id);
    wfPage  = await createConfluencePage('CSTS — Wireframes',              WIREFRAMES_CONTENT, archPage?.id);
    console.log('[documentation] HLD + LLD + Wireframes published.');
  } catch (err) {
    warnings.push(`HLD/LLD/Wireframes: ${err.message}`);
    console.warn(`[documentation] HLD/LLD/Wireframes failed (non-fatal): ${err.message}`);
  }

  // ── Step 3: FRD → Confluence ───────────────────────────────────────────────
  console.log('[documentation] Step 3/5 — Publishing FRD to Confluence...');
  let frd;
  try {
    frd = await createConfluencePage('CSTS — Functional Requirements Document (FRD)', FRD_CONTENT);
    console.log(`[documentation] FRD → ${CONF_BASE + frd._links?.webui}`);
  } catch (err) {
    warnings.push(`FRD: ${err.message}`);
    console.warn(`[documentation] FRD failed (non-fatal): ${err.message}`);
  }

  // ── Step 4: API docs → Confluence (child of FRD) ─────────────────────────
  console.log('[documentation] Step 4/5 — Publishing API Documentation...');
  try {
    await createConfluencePage('CSTS — API Documentation', API_DOCS_CONTENT, frd?.id);
    console.log('[documentation] API docs published.');
  } catch (err) {
    warnings.push(`API docs: ${err.message}`);
    console.warn(`[documentation] API docs failed (non-fatal): ${err.message}`);
  }

  // ── Step 5: README.md → commit to feature branch (codebase artifact) ──────
  console.log(`[documentation] Step 5/5 — Committing README.md to branch "${targetBranch}"...`);
  const readmeContent = buildReadmeContent(state);
  let readmeUrl;
  try {
    // Also write locally so the working tree stays in sync
    const localPath = path.join(__dirname, '../../README.md');
    fs.writeFileSync(localPath, readmeContent, 'utf8');

    // Commit via GitHub API so it lands on the feature branch / PR
    await commitFile(
      targetBranch,
      'README.md',
      readmeContent,
      'docs: update README with AI-enhanced CSTS documentation'
    );
    readmeUrl = fileUrl(targetBranch, 'README.md');
    console.log(`[documentation] README.md committed → ${readmeUrl}`);
  } catch (err) {
    warnings.push(`README: ${err.message}`);
    console.warn(`[documentation] README commit failed (non-fatal): ${err.message}`);
    readmeUrl = null;
  }

  // ── Summary ────────────────────────────────────────────────────────────────
  console.log('\n[documentation] ✅ Documentation phase complete.');
  if (warnings.length > 0) {
    console.warn(`[documentation] ⚠️  ${warnings.length} warning(s):`);
    warnings.forEach(w => console.warn(`  - ${w}`));
  }
  console.log('[documentation] HITL REVIEW REQUIRED — Review docs in Confluence and README in the PR before proceeding to Testing.');

  return {
    architectureId:  archPage?.id  || null,
    architectureUrl: archPage ? CONF_BASE + archPage._links?.webui : null,
    hldId:           hldPage?.id   || null,
    hldUrl:          hldPage  ? CONF_BASE + hldPage._links?.webui  : null,
    lldId:           lldPage?.id   || null,
    lldUrl:          lldPage  ? CONF_BASE + lldPage._links?.webui  : null,
    wireframesId:    wfPage?.id    || null,
    wireframesUrl:   wfPage   ? CONF_BASE + wfPage._links?.webui   : null,
    frdId:           frd?.id       || null,
    frdUrl:          frd      ? CONF_BASE + frd._links?.webui      : null,
    confluenceUrl:   frd      ? CONF_BASE + frd._links?.webui      : null,
    readmeUrl,
    branch:          targetBranch,
    warnings,
  };
}

module.exports = { run };

if (require.main === module) {
  run().catch(err => { console.error('[documentation] Failed:', err.message); process.exit(1); });
}
